//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/HyperCasualRunner/Input/CoreGameplay.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CoreGameplay: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CoreGameplay()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CoreGameplay"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""4781dae4-208e-4df8-b35e-fb6c6abc3bab"",
            ""actions"": [
                {
                    ""name"": ""PrimaryTouchPositionInScreenSpace"",
                    ""type"": ""Value"",
                    ""id"": ""d9ea2453-dca6-4026-bcb2-1668f75566e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fd8b2ec9-66b3-418f-a623-daf713b11248"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchPositionInScreenSpace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_PrimaryTouchPositionInScreenSpace = m_Touch.FindAction("PrimaryTouchPositionInScreenSpace", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
    private readonly InputAction m_Touch_PrimaryTouchPositionInScreenSpace;
    public struct TouchActions
    {
        private @CoreGameplay m_Wrapper;
        public TouchActions(@CoreGameplay wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryTouchPositionInScreenSpace => m_Wrapper.m_Touch_PrimaryTouchPositionInScreenSpace;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void AddCallbacks(ITouchActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
            @PrimaryTouchPositionInScreenSpace.started += instance.OnPrimaryTouchPositionInScreenSpace;
            @PrimaryTouchPositionInScreenSpace.performed += instance.OnPrimaryTouchPositionInScreenSpace;
            @PrimaryTouchPositionInScreenSpace.canceled += instance.OnPrimaryTouchPositionInScreenSpace;
        }

        private void UnregisterCallbacks(ITouchActions instance)
        {
            @PrimaryTouchPositionInScreenSpace.started -= instance.OnPrimaryTouchPositionInScreenSpace;
            @PrimaryTouchPositionInScreenSpace.performed -= instance.OnPrimaryTouchPositionInScreenSpace;
            @PrimaryTouchPositionInScreenSpace.canceled -= instance.OnPrimaryTouchPositionInScreenSpace;
        }

        public void RemoveCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnPrimaryTouchPositionInScreenSpace(InputAction.CallbackContext context);
    }
}
